# Generated by Django 4.2.2 on 2023-06-09 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='promocao',
            name='empresa',
        ),
    ]
