# Generated by Django 3.2.19 on 2023-06-12 12:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_promocao_empresa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loja',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='empresa', to='api.empresa'),
        ),
        migrations.AlterField(
            model_name='promocao',
            name='loja',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loja', to='api.loja'),
        ),
    ]
